code/dp
karthikdatta123/Owner-App pull request #3
Opened 2022-02-03 14:41 UTC by dhairyapasrija5

2022-02-04 15:22 UTC, karthikdatta123 requested changes
1. remove this file Owner App.zip
2. keep variable name descriptive not a, b
3. use api for getting data instead of hardcoding
4. avoid blank lines

2022-02-04 15:22 UTC, karthikdatta123 commented on app/src/main/java/com/example/ownerapp/CustomAdapter.java
> +    public CustomAdapter(Activity activity,List<Orders> a){
keep variable names readable instead of a

2022-02-04 15:22 UTC, karthikdatta123 commented on app/src/main/java/com/example/ownerapp/CustomAdapter.java
> +
check format. avoid extra spaces

2022-02-04 15:22 UTC, karthikdatta123 commented on app/src/main/java/com/example/ownerapp/MainActivity.java
> +        room1.items.add("South Indian Thali");
why hardcoded? just for now? try to get this data from api. you can use mock apis for now

2022-02-04 15:22 UTC, karthikdatta123 commented on app/src/main/java/com/example/ownerapp/MainActivity.java
> +        CustomAdapter c=new CustomAdapter(this,list);
varable name

2022-02-12 17:07 UTC, ankithakini23 approved these changes

2022-02-12 17:07 UTC, ankithakini23 commented on app/src/main/java/com/example/ownerapp/MainActivity.java
>  import androidx.fragment.app.FragmentTransaction;
Remove spaces

2022-02-12 17:07 UTC, ankithakini23 commented on app/src/main/java/com/example/ownerapp/RoomAdapter.java
> +                           // mDatabaseReference.removeEventListener(myListener);
why is this method empty

2022-02-12 17:07 UTC, merged